version: '3'
services:
  api:
    container_name: referral
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - fullstack

  postgres:
    image: postgres:9.6
    container_name: postgres-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=referral_service
      - POSTGRES_USER=referral
      - POSTGRES_PASSWORD=referral
      - POSTGRES_PORT=5432
    volumes:
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fullstack

volumes:
  api:
  postgres:

networks:
  fullstack:
    driver: bridge